name: sdfsync

on:
  push:
    branches:
      - 'sandbox'

jobs:
  # You can also do one for sandbox. Just make sure NSENV is packages/sandbox
  production:
    runs-on: ubuntu-latest
    # This is where your secrets environment is pulled from.
    environment: SANDBOX
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
      - name: production-sync
        uses: christopherwxyz/sdfsync@0.0.24
        env:
          ACCOUNT: YOURACCOUNT
          # Make sure AUTHID matches to sandbox
          AUTHID: PRODUCTION
          URL: 12345678.app.netsuite.com
          GITURL: git@github.com-alias:yourcompany/suitecloud-example-repo.git
          NSENV: packages/sandbox
          EXCLUDED: savedsearch,csvimport,dataset,financiallayout,reportdefinition,translationcollection,workbook
          SLOW: ""
          TOKENID: ${{ secrets.TOKENID }}
          TOKENSECRET: ${{ secrets.TOKENSECRET }}
          WORKSPACE: /github/workspace
      - name: Sync commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: Production sync
      - name: Set user
        run: sudo chown -R $USER:$USER .
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: Sync with production
            author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
            title: Sync with production
            body: |
              - Sync with production

              Auto-generated by [create-pull-request][1]

              [1]: https://github.com/peter-evans/create-pull-request
            labels: sync, automerge
            branch: production